config/routes.rb
Rails.application.routes.draw do

  namespace :agential, defaults: { business: 'agential' } do
    namespace :admin, defaults: { namespace: 'admin' } do
      resources :agencies do
        member do
          get 'crowd' => :edit_crowd
          patch 'crowd' => :update_crowd
          delete 'crowd' => :destroy_crowd
          delete 'card' => :destroy_card
        end
      end
    end

    namespace :my, defaults: { namespace: 'my' } do
      resources :agencies
    end

    namespace :me, defaults: { namespace: 'me' } do
      resources :agencies
    end

  end

end

app/models/agential/agency.rb
module Agential
  class Agency < ApplicationRecord
    include Model::Agency
  end
end

app/models/agential/model/agency.rb
module Agential
  module Model::Agency
    extend ActiveSupport::Concern

    included do
      attribute :relation, :string, default: 'unknown'
      attribute :commission_ratio, :decimal, precision: 4, scale: 2, comment: '交易时抽成比例'
      attribute :note, :string, comment: '备注'

      belongs_to :agent, class_name: 'Auth::User'
      belongs_to :client, class_name: 'Profiled::Profile'

      accepts_nested_attributes_for :client, reject_if: :all_blank

      enum relation: options_i18n(:relation).values.map { |i| [i.to_sym, i.to_s] }.to_h
    end

    def name
      "#{relation_i18n} #{client.name}"
    end

  end
end

app/controllers/agency/mine/agencies_controller.rb
class Agency::Mine::AgenciesController < Agency::Mine::BaseController
  before_action :set_agency, only: [:show, :edit, :update, :destroy]

  def index
    @agencies = current_user.agencies.includes(:client).page(params[:page])
  end

  def new
    @agency = current_user.agencies.build
    @agency.build_client
  end

  def create
    @agency = current_user.agencies.build(agency_params)

    if @agency.save
      render 'create', locals: { return_to: mine_agencies_url }
    else
      render :new, locals: { model: @agency }, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    @agency.assign_attributes(agency_params)

    unless @agency.save
      render :edit, locals: { model: @agency }, status: :unprocessable_entity
    end
  end

  def destroy
    @agency.destroy
  end

  private
  def set_agency
    @agency = Agency.find(params[:id])
  end

  def client_params
    params.fetch(:client, {}).permit(
      :real_name,
      :nick_name,
      :birthday_type,
      :birthday,
      :gender,
      :note,
      :avatar,
      agencies_attributes: {}
    )
  end

  def agency_params
    params.fetch(:agency, {}).permit(
      :relation,
      :client_type,
      :commission_ratio,
      :note,
      client_attributes: {}
    )
  end

end

app/controllers/agential/admin/agencies_controller.rb
module Agential
  class Admin::AgenciesController < Admin::BaseController
    before_action :set_agency, only: [
      :show, :edit, :update,
      :edit_crowd, :update_crowd, :destroy_crowd, :destroy_card,
      :destroy
    ]

    def index
      q_params = {}
      #q_params.merge! default_params
      #q_params.merge! member_id: current_member.id if current_member
      q_params.merge! params.permit('client.real_name')

      @agencies = Agency.distinct.joins(:cards).where.not(cards: { id: nil }).default_where(q_params).order(id: :desc).page(params[:page])
    end

    def edit_crowd
      q_params = {
        'id-not': @agency.crowd_ids
      }
      q_params.merge! default_params
      @crowds = Crowd.default_where(q_params)
    end

    def update_crowd
      if @agency.join_crowd params[:crowd_id]
        render 'update'
      else
        render :edit_crowd, locals: { model: @agency }, status: :unprocessable_entity
      end
    end

    def destroy_crowd
      cs = @agency.crowd_members.find_by(crowd_id: params[:crowd_id])
      if cs&.destroy
        render 'update'
      end
    end

    def destroy_card
      card = @agency.cards.find(params[:card_id])
      card.agency = nil
      card.client = nil

      if card.save
        render 'update'
      end
    end

    private
    def set_agency
      @agency = Agency.find(params[:id])
    end

    def agency_params
      params.fetch(:agency, {}).permit(
        :real_name,
        :gender,
        :note
      )
    end

  end
end

app/controllers/agential/me/agencies_controller.rb
module Agential
  class Me::AgenciesController < Me::BaseController
    before_action :set_agency, only: [:show, :edit, :update, :destroy]

    def index
      @agencies = current_agent.agencies.includes(:client).page(params[:page])
    end

    def new
      @agency = current_agent.agencies.build
    end

    def create
      @agency = current_agent.agencies.build(agency_params)

      unless @agency.save
        render :new, locals: { model: @agency }, status: :unprocessable_entity
      end
    end

    def show
    end

    def edit
    end

    def update
      @agency.assign_attributes(agency_params)

      unless @agency.save
        render :edit, locals: { model: @agency }, status: :unprocessable_entity
      end
    end

    def destroy
      @agency.destroy
    end

    private
    def set_agency
      @agency = Agency.find(params[:id])
    end

    def client_params
      params.fetch(:profile, {}).permit(
        :real_name,
        :nick_name,
        :birthday_type,
        :birthday,
        :gender,
        :note,
        :avatar,
        agencies_attributes: {}
      )
    end

    def agency_params
      params.fetch(:agency, {}).permit(
        :relation,
        :client_type,
        :client_id,
        :commission_ratio,
        :note,
        client_attributes: {}
      )
    end

  end
end

app/controllers/agential/me/base_controller.rb
module Agential
  class Me::BaseController < MeController

    def current_agent
      current_member
    end

  end
end

app/controllers/agential/my/agencies_controller.rb
module Agential
  class My::AgenciesController < My::BaseController
    before_action :set_agency, only: [:show, :edit, :update, :destroy]

    def index
      @agencies = current_user.agencies.includes(:client).page(params[:page])
    end

    def new
      @agency = current_user.agencies.build
      @agency.build_client
    end

    def create
      @agency = current_user.agencies.build(agency_params)

      if @agency.save
        render 'create', locals: { return_to: url_for(action: 'index') }
      else
        render :new, locals: { model: @agency }, status: :unprocessable_entity
      end
    end

    private
    def set_agency
      @agency = Agency.find(params[:id])
    end

    def client_params
      params.fetch(:client, {}).permit(
        :real_name,
        :nick_name,
        :birthday_type,
        :birthday,
        :gender,
        :note,
        :avatar,
        agencies_attributes: {}
      )
    end

    def agency_params
      params.fetch(:agency, {}).permit(
        :relation,
        :client_type,
        :commission_ratio,
        :note,
        client_attributes: {}
      )
    end

  end
end

app/views/agential/me/agencies/_client_form.html.erb
<%= f.fields :client do |ef| %>
  <%= ef.text_field :real_name %>
  <%= ef.text_field :nick_name %>
  <%= ef.select :birthday_type, options_for_select(Profile.options_i18n(:birthday_type)) %>
  <%= ef.date_field :birthday %>
  <%= ef.select :gender, options_for_select(Profile.options_i18n(:gender)) %>
  <%= ef.text_field :note %>
  <%= ef.file_field :avatar %>
<% end %>

app/views/agential/me/agencies/_filter.html.erb
<%= form_with theme: 'search', model: Profile.new do |f| %>
  <div class="field-body">
    <%= f.text_field :name %>
    <div class="field is-narrow">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/agential/me/agencies/_form.html.erb
<%= form_with model: [:my, @agency] do |f| %>
  <%= render 'error_messages', target: f.object %>
  <%= f.select :relation, options_for_select(Agency.options_i18n(:relation)) %>
  <%= f.number_field :commission_ratio, step: '0.01' %>
  <%= f.text_area :note %>
  <%= f.submit %>
<% end %>

app/views/agential/me/agencies/_show_table.html.erb
<table class="table is-hoverable is-fullwidth">
  <thead>
    <tr>
      <th class="six wide">
        <%= link_to t('.edit'), edit_my_pupil_path(@pupil), class: 'ui mini blue right floated button', remote: true %>
      </th>
      <th class="ten wide"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="has-text-right"><%= Pupil.human_attribute_name(:name) %></td>
      <td><%= @pupil.name %></td>
    </tr>
    <tr>
      <td class="has-text-right"><%= Pupil.human_attribute_name(:petname) %></td>
      <td><%= @pupil.petname %></td>
    </tr>
    <tr>
      <td class="has-text-right"><%= Pupil.human_attribute_name(:birthday_type) %></td>
      <td><%= @pupil.birthday_type %></td>
    </tr>
    <tr>
      <td class="has-text-right"><%= Pupil.human_attribute_name(:birthday) %></td>
      <td><%= @pupil.birthday %></td>
    </tr>
    <tr>
      <td class="has-text-right"><%= Pupil.human_attribute_name(:gender) %></td>
      <td><%= @pupil.gender %></td>
    </tr>
    <tr>
      <td class="has-text-right"><%= Pupil.human_attribute_name(:note) %></td>
      <td><%= @pupil.note %></td>
    </tr>
  </tbody>
</table>

app/views/agential/me/agencies/index.html+phone.erb
<div class="weui-panel">
  <div class="weui-panel__hd">我的宝贝</div>
  <div class="weui-panel__bd">
    <% @tutelages.each do |tutelage| %>
    <div class="weui-media-box weui-media-box_appmsg">
      <div class="weui-media-box__hd">
        <%= image_tag tutelage.pupil.avatar, class: 'weui-media-box__thumb' %>
      </div>
      <div class="weui-media-box__bd">
        <h4 class="weui-media-box__title"><%= tutelage.relation_i18n %></h4>
        <p class="weui-media-box__desc">
          <%= tutelage.pupil.real_name %>
        </p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/agential/me/agencies/index.html.erb
<%= render 'filter' %>

<table class="table is-hoverable is-fullwidth">
  <thead>
    <tr>
      <th><%= Agency.human_attribute_name(:relation) %></th>
      <th><%= Agency.human_attribute_name(:note) %></th>
      <th><%= Agency.human_attribute_name(:commission_ratio) %></th>
      <th><%= Agency.human_attribute_name('client.name') %></th>
      <th>
        <%= link_to new_my_agency_path, remote: true, class: 'button is-small is-info' do %>
          <i class="fa-light fa-plus"></i><%= t('.new') %>
        <% end %>
      </th>
    </tr>
  </thead>
  <tbody>
  <% @agencies.each do |agency| %>
    <tr>
      <td><%= agency.relation_i18n %></td>
      <td><%= agency.note %></td>
      <td><%= agency.commission_ratio %></td>
      <td>
        <%= link_to agency.client.name %>
      </td>
      <td>
        <%= link_to my_agency_path(agency), aria: { label: t('.show') }, remote: true, class: 'button is-small is-rounded is-light' do %>
          <i class="fa-light fa-circle-info"></i>
        <% end %>
        <%= link_to edit_my_agency_path(agency), aria: { label: t('.edit') }, remote: true, class: 'button is-small is-rounded is-light' do %>
          <i class="fa-light fa-pencil"></i>
        <% end %>
        <%= link_to my_agency_path(agency), method: :delete, aria: { label: t('.destroy') }, data: { confirm: t('.confirm') }, remote: true, class: 'button is-small is-rounded is-light' do %>
          <i class="fa-light fa-trash"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>