config/routes.rb
Rails.application.routes.draw do

  namespace :agential, defaults: { business: 'agential' } do
    namespace :admin, defaults: { namespace: 'admin' } do
      resources :agencies do
        member do
          get 'crowd' => :edit_crowd
          patch 'crowd' => :update_crowd
          delete 'crowd' => :destroy_crowd
          delete 'card' => :destroy_card
        end
      end
    end

    namespace :my, defaults: { namespace: 'my' } do
      resources :agencies
    end

    namespace :me, defaults: { namespace: 'me' } do
      resources :agencies
    end

  end

end

app/models/agential/agency.rb
module Agential
  class Agency < ApplicationRecord
    include Model::Agency
  end
end

app/models/agential/model/agency.rb
module Agential
  module Model::Agency
    extend ActiveSupport::Concern

    included do
      attribute :relation, :string, default: 'unknown'
      attribute :commission_ratio, :decimal, precision: 4, scale: 2, comment: '交易时抽成比例'
      attribute :note, :string, comment: '备注'

      belongs_to :agent, class_name: 'Auth::User'
      belongs_to :client, class_name: 'Profiled::Profile'

      accepts_nested_attributes_for :client, reject_if: :all_blank

      enum relation: options_i18n(:relation).values.map { |i| [i.to_sym, i.to_s] }.to_h
    end

    def name
      "#{relation_i18n} #{client.name}"
    end

  end
end

app/controllers/agency/mine/agencies_controller.rb
class Agency::Mine::AgenciesController < Agency::Mine::BaseController
  before_action :set_agency, only: [:show, :edit, :update, :destroy]

  def index
    @agencies = current_user.agencies.includes(:client).page(params[:page])
  end

  def new
    @agency = current_user.agencies.build
    @agency.build_client
  end

  def create
    @agency = current_user.agencies.build(agency_params)

    if @agency.save
      render 'create', locals: { return_to: mine_agencies_url }
    else
      render :new, locals: { model: @agency }, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    @agency.assign_attributes(agency_params)

    unless @agency.save
      render :edit, locals: { model: @agency }, status: :unprocessable_entity
    end
  end

  def destroy
    @agency.destroy
  end

  private
  def set_agency
    @agency = Agency.find(params[:id])
  end

  def client_params
    params.fetch(:client, {}).permit(
      :real_name,
      :nick_name,
      :birthday_type,
      :birthday,
      :gender,
      :note,
      :avatar,
      agencies_attributes: {}
    )
  end

  def agency_params
    params.fetch(:agency, {}).permit(
      :relation,
      :client_type,
      :commission_ratio,
      :note,
      client_attributes: {}
    )
  end

end

app/controllers/agential/admin/agencies_controller.rb
module Agential
  class Admin::AgenciesController < Admin::BaseController
    before_action :set_agency, only: [
      :show, :edit, :update,
      :edit_crowd, :update_crowd, :destroy_crowd, :destroy_card,
      :destroy
    ]

    def index
      q_params = {}
      #q_params.merge! default_params
      #q_params.merge! member_id: current_member.id if current_member
      q_params.merge! params.permit('client.real_name')

      @agencies = Agency.distinct.joins(:cards).where.not(cards: { id: nil }).default_where(q_params).order(id: :desc).page(params[:page])
    end

    def edit_crowd
      q_params = {
        'id-not': @agency.crowd_ids
      }
      q_params.merge! default_params
      @crowds = Crowd.default_where(q_params)
    end

    def update_crowd
      if @agency.join_crowd params[:crowd_id]
        render 'update'
      else
        render :edit_crowd, locals: { model: @agency }, status: :unprocessable_entity
      end
    end

    def destroy_crowd
      cs = @agency.crowd_members.find_by(crowd_id: params[:crowd_id])
      if cs&.destroy
        render 'update'
      end
    end

    def destroy_card
      card = @agency.cards.find(params[:card_id])
      card.agency = nil
      card.client = nil

      if card.save
        render 'update'
      end
    end

    private
    def set_agency
      @agency = Agency.find(params[:id])
    end

    def agency_params
      params.fetch(:agency, {}).permit(
        :real_name,
        :gender,
        :note
      )
    end

  end
end

app/controllers/agential/me/agencies_controller.rb
module Agential
  class Me::AgenciesController < Me::BaseController
    before_action :set_agency, only: [:show, :edit, :update, :destroy]

    def index
      @agencies = current_agent.agencies.includes(:client).page(params[:page])
    end

    def new
      @agency = current_agent.agencies.build
    end

    def create
      @agency = current_agent.agencies.build(agency_params)

      unless @agency.save
        render :new, locals: { model: @agency }, status: :unprocessable_entity
      end
    end

    def show
    end

    def edit
    end

    def update
      @agency.assign_attributes(agency_params)

      unless @agency.save
        render :edit, locals: { model: @agency }, status: :unprocessable_entity
      end
    end

    def destroy
      @agency.destroy
    end

    private
    def set_agency
      @agency = Agency.find(params[:id])
    end

    def client_params
      params.fetch(:profile, {}).permit(
        :real_name,
        :nick_name,
        :birthday_type,
        :birthday,
        :gender,
        :note,
        :avatar,
        agencies_attributes: {}
      )
    end

    def agency_params
      params.fetch(:agency, {}).permit(
        :relation,
        :client_type,
        :client_id,
        :commission_ratio,
        :note,
        client_attributes: {}
      )
    end

  end
end

app/controllers/agential/my/agencies_controller.rb
module Agential
  class My::AgenciesController < My::BaseController
    before_action :set_agency, only: [:show, :edit, :update, :destroy]

    def index
      @agencies = current_user.agencies.includes(:client).page(params[:page])
    end

    def new
      @agency = current_user.agencies.build
      @agency.build_client
    end

    def create
      @agency = current_user.agencies.build(agency_params)

      if @agency.save
        render 'create', locals: { return_to: url_for(action: 'index') }
      else
        render :new, locals: { model: @agency }, status: :unprocessable_entity
      end
    end

    private
    def set_agency
      @agency = Agency.find(params[:id])
    end

    def client_params
      params.fetch(:client, {}).permit(
        :real_name,
        :nick_name,
        :birthday_type,
        :birthday,
        :gender,
        :note,
        :avatar,
        agencies_attributes: {}
      )
    end

    def agency_params
      params.fetch(:agency, {}).permit(
        :relation,
        :client_type,
        :commission_ratio,
        :note,
        client_attributes: {}
      )
    end

  end
end

app/views/agential/admin/agencies/_edit_crowd.html.erb
<%= render layout: 'modal' do %>
  <%= form_with url: { action: 'crowd' }, method: :patch do |f| %>
    <%= f.collection_select :crowd_id, @crowds, :id, :name %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/agential/admin/agencies/_filter_form.html.erb
<%= form_with theme: 'search', model: Agency.new do |f| %>
  <div class="field-body">
    <%= f.text_field 'pupil.real_name' %>
    <div class="field is-narrow">
      <%= f.submit %>
      <%= link_to t('.clear'), filter_params(except: ['pupil.real_name']), class: 'button is-light' %>
    </div>
  </div>
<% end %>

app/views/agential/admin/agencies/_form.html.erb
<%= render 'error_messages', target: f.object %>
<%= f.text_field :real_name %>
<%= f.text_field :age %>
<%= f.text_field :gender %>
<%= f.text_field :note %>

app/views/agential/admin/agencies/_show_table.html.erb
<table class="table is-hoverable is-fullwidth">
  <tbody>
    <tr>
      <td class="has-text-right"><%= Agency.human_attribute_name('client.real_name') %></td>
      <td><%= @agency.client.real_name %></td>
    </tr>
    <tr>
      <td class="has-text-right"><%= Agency.human_attribute_name('client.age') %></td>
      <td><%= @agency.client.age %></td>
    </tr>
    <tr>
      <td class="has-text-right"><%= Agency.human_attribute_name('client.gender') %></td>
      <td><%= @agency.client.gender %></td>
    </tr>
    <tr>
      <td class="has-text-right"><%= Agency.human_attribute_name(:note) %></td>
      <td><%= @agency.client.note %></td>
    </tr>
    <tr>
      <td class="has-text-right"><%= Agency.human_attribute_name('agent.identity') %></td>
      <td>
        <%= @agency.tutelar.identity %>
        <% if @agency.tutelar.user && @agency.tutelar.account&.wechat_response %>
          <%= image_tag @agency.tutelar.account.qrcode_url, class: 'ui small image' %>
        <% else %>
          <%= link_to qrcode_admin_profile_path(@agency.tutelar), method: :patch, remote: true, id: 'account_qrcode' do %>
            <i class="fa-light fa-qrcode"></i>
          <% end %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

app/views/agential/admin/agencies/edit_crowd.html.erb
<turbo-frame id="modal">
  <%= form_with url: { action: 'crowd' }, method: :patch do |f| %>
    <%= f.collection_select :crowd_id, @crowds, :id, :name %>
    <%= f.submit %>
  <% end %>
</turbo-frame>

app/views/agential/admin/agencies/index.html.erb
<td><%= model.client.real_name %></td>
<td><%= model.client.age %></td>
<td>
  <span class="ui icon label">
    <i class="fa-light <%= model.client.male? ? 'fa-male' : 'fa-female' %>"></i>
    <%= model.client.gender_i18n %>
  </span>
</td>
<td><%= model.client.note %></td>
<td>
  <% model.crowds.each do |crowd| %>
    <div class="ui image label">
      <%= image_tag crowd.logo if crowd.logo.present? %>
      <%= crowd.name %>
      <%= link_to crowd_admin_agency_path(model, crowd_id: crowd.id), method: :delete, remote: true do %>
        <i class="delete icon"></i>
      <% end %>
    </div>
  <% end %>
  <%= link_to crowd_admin_agency_path(model), aria: { label: '分班' }, class: 'button is-small is-rounded is-light', remote: true do %>
    <i class="hand point right icon"></i>
  <% end %>
</td>
<td>
  <% model.cards.each do |card| %>
    <div class="ui image label">
      <%= link_to card.card_uuid, admin_card_card_logs_path(card), text: true %>
      <%= link_to card_admin_agency_path(model, card_id: card.id), method: :delete do %>
        <i class="delete icon"></i>
      <% end %>
    </div>
  <% end %>
</td>
<td>
  <%= link_to admin_agency_path(model), class: 'button is-small is-rounded is-light', remote: true do %>
    <i class="fa-light fa-circle-info"></i>
  <% end %>
</td>